### PR TITLE
minor edits, closing paragraph

### PR DESCRIPTION
**Pull request by burritojustice**

### CODE REVIEW

**Comment by kevinkreiser** [comment]
:shipit:

**Comment by dnesbitt61** [comment]
looks good, thanks

**Comment by burritojustice** [comment]
is that a squirrel wearing a hat

**Comment by burritojustice** [comment]
ah ha it is a squirrel wearing hat

**Comment by burritojustice** [comment]
i demand a gif of said squirrel

**Comment by dnesbitt61** [comment]
that means "shipit". Search github shipit squirrel for more info

**Comment by burritojustice** [comment]
that was a really, really good post btw. probably need another sentence or two in the final paragraph, and maybe another link back to the repo. any more detailed comment on timing?

**Comment by burritojustice** [comment]
ahhhhh ok. sorry I am gloriously naive re github and I am still on the steep part of the learning curve

**Pull request merged**
