### PR TITLE
use localhost when we say

### PR DESCRIPTION
**Pull request by kevinkreiser**

### CODE REVIEW

**Comment by dnesbitt61** [comment]
If I am just running a local Valhalla route service how can I get elevation charts from dev?

**Comment by kevinkreiser** [comment]
there is a larger issue that we have default skadi service and tyr service on 8002. we could change the port of one of them and that would fix it but its a bit more complicated because we hvae to think about what to do with chef which currently doesnt have to care

**Comment by dnesbitt61** [comment]
:shipit

**Comment by kdiluca** [comment]
:+1:

**Pull request merged**
